/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.capaCliente.VISTA;

import org.itson.capaCliente.PRESENTADOR.IPresentadorCrearSala;
import org.itson.capaCliente.PRESENTADOR.IPresentadorMenuPrincipal;

/**
 *
 * @author equipo 1
 */
public class FrmCrearSala extends javax.swing.JFrame {

    /**
     * Creates new form FrmCrearSala
     */
    IPresentadorCrearSala presentadorC;
    
    public FrmCrearSala(IPresentadorCrearSala presentadorC) {
        initComponents();
        this.presentadorC = presentadorC;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNumJugadores = new javax.swing.JLabel();
        cmbJugadores = new javax.swing.JComboBox<>();
        btnCrearPartida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/return.png"))); // NOI18N
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setFocusable(false);
        btnReturn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/return.png"))); // NOI18N
        btnReturn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/return.png"))); // NOI18N
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 73, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumJugadores.setText("Número de jugadores");
        jPanel1.add(lblNumJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        cmbJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", " " }));
        cmbJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbJugadoresActionPerformed(evt);
            }
        });
        jPanel1.add(cmbJugadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 170, -1));

        btnCrearPartida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Botón Crear.png"))); // NOI18N
        btnCrearPartida.setBorderPainted(false);
        btnCrearPartida.setContentAreaFilled(false);
        btnCrearPartida.setFocusable(false);
        btnCrearPartida.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Botón Crear.png"))); // NOI18N
        btnCrearPartida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botones/Botón Crear.png"))); // NOI18N
        btnCrearPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearPartidaMouseEntered(evt);
            }
        });
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        presentadorC.regresarMenu();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void cmbJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbJugadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbJugadoresActionPerformed

    private void btnCrearPartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPartidaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPartidaMouseEntered

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
//        presentadorC.crearCodigo();
        presentadorC.apareceSigAjustes();
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmCrearSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmCrearSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmCrearSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmCrearSala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmCrearSala().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnReturn;
    private javax.swing.JComboBox<String> cmbJugadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNumJugadores;
    // End of variables declaration//GEN-END:variables
}
