/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.capaCliente.VISTA;

import java.awt.Color;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;
import org.itson.capaCliente.PRESENTADOR.IPresentadorJuego;
import org.itson.capaCliente.VISTAG.TableroGrafico;
import org.itson.capadominio.Jugador;
import org.itson.capadominio.Tablero;

/**
 *
 * @author hoshi
 */
public class FrmJuego extends javax.swing.JFrame {

    /**
     * Creates new form FrmJuego
     */
    TableroGrafico tablero;
    IPresentadorJuego presentadorJ;
    
    public FrmJuego(IPresentadorJuego presentadorJ) {
        this.presentadorJ = presentadorJ;
        tablero = new TableroGrafico(new Tablero(),new Jugador());
        initComponents();
        
        ELPEPEpanel.add(tablero);
        tablero.setBackground(new Color(153,204,255));
        tablero.setSize(ELPEPEpanel.getSize());
//        this.setContentPane(tablero);
//        this.setContentPane(jPanel1);
        
//        tablero.setActionMap(jPanel1.getActionMap());
//        this.jPanel1.add(tablero);
//        this.tablero.setVisible(true);
//        this.repaint();
    }
    
    public void tableroPanel(){
        System.out.println("loq sea");
    }
    
    public void setJugador(Jugador jugador) {
        tablero.setJugador(jugador);
    }

    public void mandarTablero() {
        Tablero tablerito = presentadorJ.regresarTablero();
        tablero.setTablero(tablerito);
        tablero.crearTableroGrafico();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ELPEPEpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(682, 402));
        setPreferredSize(new java.awt.Dimension(1200, 604));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ELPEPEpanel.setBackground(new java.awt.Color(153, 204, 255));
        ELPEPEpanel.setPreferredSize(new java.awt.Dimension(650, 570));
        ELPEPEpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ELPEPEpanelMouseMoved(evt);
            }
        });
        ELPEPEpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ELPEPEpanelMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ELPEPEpanelLayout = new javax.swing.GroupLayout(ELPEPEpanel);
        ELPEPEpanel.setLayout(ELPEPEpanelLayout);
        ELPEPEpanelLayout.setHorizontalGroup(
            ELPEPEpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        ELPEPEpanelLayout.setVerticalGroup(
            ELPEPEpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(ELPEPEpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 690, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMousePressed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
       
    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void ELPEPEpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ELPEPEpanelMousePressed
        // TODO add your handling code here:
        tablero.verificarLinea(evt);
    }//GEN-LAST:event_ELPEPEpanelMousePressed

    private void ELPEPEpanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ELPEPEpanelMouseMoved
        // TODO add your handling code here:
        tablero.pintarLineaPanthom(evt);
    }//GEN-LAST:event_ELPEPEpanelMouseMoved

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmJuego().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ELPEPEpanel;
    // End of variables declaration//GEN-END:variables
}
