/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.capaCliente.VISTA;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import org.itson.capaCliente.PRESENTADOR.IPresentadorSalaEspera;
import org.itson.capadominio.Jugador;

/**
 *
 * @author Equipo 1
 */
public class FrmSalaEspera extends javax.swing.JFrame {

    /**
     * Creates new form FrmSalaJugadores
     */ 
    private IPresentadorSalaEspera presentadorS;
    
    public FrmSalaEspera(IPresentadorSalaEspera presentadorS) {
        initComponents();
        Color color = new Color(0,0,0,0); 
        botonseguir.setBackground(color);
        this.presentadorS = presentadorS;
        
        
//        imagenSeleccionada = ajustes.getImagenSeleccionada();
//        if (imagenSeleccionada != null) {
//            lblJugador1.setIcon(imagenSeleccionada); // Asegúrate de que lbl esté configurado correctamente
//        }
//        System.out.println(imagenSeleccionada);
    }

    
    
    public void MostrarJugador(){
        
        Jugador jugador =presentadorS.regresarJugador();
        if (jugador==null){
            return;
        }
        lblJugador1.setText(jugador.getNombre());
       ImageIcon icon = new ImageIcon(getClass().getResource("/avatares/"+jugador.getAvatar()));
       lblAvatar.setIcon(icon);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReturn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAvatar = new javax.swing.JLabel();
        botonseguir = new javax.swing.JButton();
        lblJugador1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/return.png"))); // NOI18N
        btnReturn.setBorderPainted(false);
        btnReturn.setContentAreaFilled(false);
        btnReturn.setFocusable(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 73, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, 180));

        botonseguir.setBackground(new java.awt.Color(242, 242, 242));
        botonseguir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/felchaAdelante.png"))); // NOI18N
        botonseguir.setBorderPainted(false);
        botonseguir.setFocusPainted(false);
        botonseguir.setFocusable(false);
        botonseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonseguirActionPerformed(evt);
            }
        });
        jPanel1.add(botonseguir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 60, 40));
        jPanel1.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        presentadorS.abrirPantallaAnterior();

    }//GEN-LAST:event_btnReturnActionPerformed

    private void botonseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonseguirActionPerformed

        presentadorS.abrirPantallaJuego();
    }//GEN-LAST:event_botonseguirActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmSalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmSalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmSalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmSalaEspera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmSalaEspera().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonseguir;
    private javax.swing.JButton btnReturn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblJugador1;
    // End of variables declaration//GEN-END:variables
}
