/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.itson.capaCliente.VISTA;

import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import org.itson.capaCliente.PRESENTADOR.IPresentadorSalaPuntaje;
import org.itson.capadominio.Jugador;

/**
 * Clase FrmSalaPuntuacion: Representa la interfaz gráfica que muestra la puntuación final
 * de los jugadores al finalizar una partida en la sala.
 * La clase está diseñada para ser utilizada en conjunto con un presentador de sala de puntuación (IPresentadorSalaPuntaje).
 * 
 * @author Equipo 1
 */
public class FrmSalaPuntuacion extends javax.swing.JFrame {

    // Variable para almacenar el presentador de sala de puntuación
    private IPresentadorSalaPuntaje presentadorS;

    /**
     * Constructor de la clase FrmSalaPuntuacion.
     * Inicializa los componentes de la interfaz gráfica y configura el presentador de sala de puntuación.
     * 
     * @param presentadorS Implementación de la interfaz IPresentadorSalaPuntaje que manejará la lógica de la sala de puntuación.
     */
    public FrmSalaPuntuacion(IPresentadorSalaPuntaje presentadorS) {
        initComponents();
        this.presentadorS = presentadorS;
    }
    
    public void MostrarJugador() {
        List<Jugador> jugadores = presentadorS.regresarJugadores();
        if (jugadores.isEmpty()) {
            return;
        }

        for (int i = 0; i < jugadores.size(); i++) {
            if (i == 0) {
                lblJugador1.setText(jugadores.get(0).getNombre());
                ImageIcon icon = new ImageIcon(getClass().getResource("/avatares/" + jugadores.get(0).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(icon.getImage().getScaledInstance(lblAvatar1.getWidth(), lblAvatar1.getHeight(), Image.SCALE_SMOOTH));
                lblAvatar1.setIcon(iconoRedimensionado);
            }
            if (i == 1) {
                lblJugador2.setText(jugadores.get(1).getNombre());
                ImageIcon icon = new ImageIcon(getClass().getResource("/avatares/" + jugadores.get(1).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(icon.getImage().getScaledInstance(lblAvatar2.getWidth(), lblAvatar2.getHeight(), Image.SCALE_SMOOTH));
                lblAvatar2.setIcon(iconoRedimensionado);
            }
            if (i == 2) {
                lblJugador3.setText(jugadores.get(2).getNombre());
                ImageIcon icon = new ImageIcon(getClass().getResource("/avatares/" + jugadores.get(2).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(icon.getImage().getScaledInstance(lblAvatar3.getWidth(), lblAvatar3.getHeight(), Image.SCALE_SMOOTH));
                lblAvatar3.setIcon(iconoRedimensionado);
            }
            if (i == 3) {
                lblJugador4.setText(jugadores.get(3).getNombre());
                ImageIcon icon = new ImageIcon(getClass().getResource("/avatares/" + jugadores.get(3).getAvatar()));
                ImageIcon iconoRedimensionado = new ImageIcon(icon.getImage().getScaledInstance(lblAvatar4.getWidth(), lblAvatar4.getHeight(), Image.SCALE_SMOOTH));
                lblAvatar4.setIcon(iconoRedimensionado);
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tercer_lugar = new javax.swing.JPanel();
        lblAvatar3 = new javax.swing.JLabel();
        lblJugador3 = new javax.swing.JLabel();
        lblPuntuacion3 = new javax.swing.JLabel();
        primer_lugar = new javax.swing.JPanel();
        lblAvatar1 = new javax.swing.JLabel();
        lblJugador1 = new javax.swing.JLabel();
        lblPuntuacion1 = new javax.swing.JLabel();
        cuarto_lugar = new javax.swing.JPanel();
        lblAvatar4 = new javax.swing.JLabel();
        lblJugador4 = new javax.swing.JLabel();
        lblPuntuacion4 = new javax.swing.JLabel();
        segundo_lugar = new javax.swing.JPanel();
        lblAvatar2 = new javax.swing.JLabel();
        lblJugador2 = new javax.swing.JLabel();
        lblPuntuacion2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/return.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Group 10.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 480, 100, 100));

        jLabel1.setText("REPLAY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Group 11.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tercer_lugar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        tercer_lugar.add(lblAvatar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 66, 58));
        tercer_lugar.add(lblJugador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 187, 28));
        tercer_lugar.add(lblPuntuacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 20));

        jPanel1.add(tercer_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 480, 70));

        primer_lugar.setBackground(new java.awt.Color(255, 204, 0));
        primer_lugar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        primer_lugar.add(lblAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 66, 58));
        primer_lugar.add(lblJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 187, 28));
        primer_lugar.add(lblPuntuacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 20));

        jPanel1.add(primer_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 480, 70));

        cuarto_lugar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        cuarto_lugar.add(lblAvatar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 66, 58));
        cuarto_lugar.add(lblJugador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 187, 28));
        cuarto_lugar.add(lblPuntuacion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 20));

        jPanel1.add(cuarto_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 480, 70));

        segundo_lugar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        segundo_lugar.add(lblAvatar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 66, 58));
        segundo_lugar.add(lblJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 187, 28));
        segundo_lugar.add(lblPuntuacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 60, 20));

        jPanel1.add(segundo_lugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 480, 70));

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        jLabel3.setText("PUNTUACIÓN FINAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 340, 60));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 0, 18)); // NOI18N
        jLabel4.setText("Felicidades ahora eres vocal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
//        presentadorS.jugarOtraVez();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * 
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         presentadorS.terminarPartida();
    }//GEN-LAST:event_jButton2ActionPerformed

    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmSalaPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmSalaPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmSalaPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmSalaPuntuacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmSalaPuntuacion().setVisible(true);
//            }
//        });
//    }

    /**
     * 
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cuarto_lugar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAvatar1;
    private javax.swing.JLabel lblAvatar2;
    private javax.swing.JLabel lblAvatar3;
    private javax.swing.JLabel lblAvatar4;
    private javax.swing.JLabel lblJugador1;
    private javax.swing.JLabel lblJugador2;
    private javax.swing.JLabel lblJugador3;
    private javax.swing.JLabel lblJugador4;
    private javax.swing.JLabel lblPuntuacion1;
    private javax.swing.JLabel lblPuntuacion2;
    private javax.swing.JLabel lblPuntuacion3;
    private javax.swing.JLabel lblPuntuacion4;
    private javax.swing.JPanel primer_lugar;
    private javax.swing.JPanel segundo_lugar;
    private javax.swing.JPanel tercer_lugar;
    // End of variables declaration//GEN-END:variables
}
